### ISSUE TITLE
求助！！

### ISSUE THREAD

**Issue by qp910** [soaph/OpenCVTest#1]
我是按照你的cmake配置的ndk环境，现在我用AndroidStudio直接run到手机上，没有任何问题，但是我打包成正式包安装到手机 就会闪退，这种情况可能是哪儿的错？！

**Comment by soaph** [comment]
@qp910 闪退的时候有什么提示吗？如果提示camera locked什么的，就是系统没有给这个应用摄像头权限，这个可以通过系统的Settings->Apps->OpenCVTest->Permissions里面勾选Camera来解决。

我这里只遇到了上述的情况，如果是其他的提示的话，我也不清楚了，我也是Android新手，不好意思：）

**Comment by qp910** [comment]
不是权限的问题，我确实奇怪，到现在还没弄清楚，为啥直接run没有问题，打正式包安装就闪退，(正式包没混淆)打正式包不报错直接闪退，同样谢谢了，我估计是cmake的配置问题

**Comment by soaph** [comment]
@qp910 既然不是这个repo本身的问题，那我就把这个issue关闭了。

**Comment by qp910** [comment]
哎呀，你直接关了 我还怎么跟你聊天 哈哈
